### ISSUE TITLE
Portals cannot display the user name when login using credentials file

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1015]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1101" title="SCHEDULING-1101">Original issue</a> created by <a href="mailto:arnaud.contes_AT_activeeon.com">Arnaud Contes</a> on 07, Feb 2011 at 10:44 AM - SCHEDULING-1101

<hr />

Use case : be able to know/track to who a connection belongs to 

Currently there is 2 connection methods available :  login/password and credential file.
when using login/password it is easy to know on the scheduler's client which user is going to connect to the scheduler.

However when a credential is used to connect to the scheduler, a client like the web interface is not able to know which user is authenticated. 
In the credential file, the CredData object is ciphered thus it is not possible to know which user is authenticated by a given credential, only the scheduler can decrypt it.

A simple solution would be to add the username in clear in the credential.
An other one would be to have the scheduler able to return the user associated with a given connection

**Comment by fviale** [comment]
fixed by https://github.com/ow2-proactive/scheduling/commit/48fafed7c561d012c3d4e5dc0f2d9787469b76d4
