### ISSUE TITLE
get access to task info/name from within the java executable

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1375]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1558" title="SCHEDULING-1558">Original issue</a> created by <a href="mailto:arnaud.contes_AT_activeeon.com">Arnaud Contes</a> on 12, Mar 2012 at 14:15 PM - SCHEDULING-1558

<hr />

I have not found if this is possible right now.
If not, this would be great to have.

**Comment by fviale** [comment]
it is now possible to access Task name using the job variables
