### ISSUE TITLE
Preserve logs encoding

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1576]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1789" title="SCHEDULING-1789">Original issue</a> created by <a href="mailto:vladimir.bodnartchouk_AT_activeeon.com">Vladimir Bodnartchouk</a> on 11, Apr 2013 at 15:36 PM - SCHEDULING-1789

<hr />

Example using 3.3.2 release

Submit a native task that runs the command "cmd.exe /c dir"

In the 1.3.2 studio the job output is:
Please wait while downloading logs...
(link: task_1@192.168.1.62;14:55:57)  Le volume dans le lecteur C n'a pas de nom. 
(link: task_1@192.168.1.62;14:55:57)  Le num,ro de s,rie du volume est CC77-C44D 
(link: task_1@192.168.1.62;14:55:57)  R,pertoire de C:\Documents and Settings\user
(link: task_1@192.168.1.62;14:55:57) 08/04/2013  16:18    <REP>          . 
(link: task_1@192.168.1.62;14:55:57) 08/04/2013  16:18    <REP>          .. 
(link: task_1@192.168.1.62;14:55:57) 31/05/2012  17:06    <REP>          .argouml 
(link: task_1@192.168.1.62;14:55:57) 20/10/2010  16:46               126 .bash_history 
(link: task_1@192.168.1.62;14:55:57) 01/02/2013  19:58             1y110 .codesigner.cfg 
(link: task_1@192.168.1.62;14:55:57) 12/11/2012  01:00                20 .erlang.cookie 
(link: task_1@192.168.1.62;14:55:57) 31/07/2012  19:45               185 .gitconfig 
(link: task_1@192.168.1.62;14:55:57) 28/11/2012  16:01    <REP>          .IntelliJIdea11 
(link: task_1@192.168.1.62;14:55:57) 20/11/2012  17:17    <REP>          .jruby 
(link: task_1@192.168.1.62;14:55:57) 17/06/2010  13:57               175 .location_of_StrapAlign.ini 
(link: task_1@192.168.1.62;14:55:57) 08/11/2012  16:52    <REP>          .nbi 
(link: task_1@192.168.1.62;14:55:57) 31/08/2012  14:04    <REP>          .nbprofiler 
(link: task_1@192.168.1.62;14:55:57) 16/10/2012  16:33    <REP>          .netbeans 
(link: task_1@192.168.1.62;14:55:57) 04/03/2013  18:13    <REP>          .nxshell 
(link: task_1@192.168.1.62;14:55:57) 11/04/2013  12:19    <REP>          .proactive 
(link: task_1@192.168.1.62;14:55:57) 07/02/2013  20:25    <REP>          .ProActive_ResourceManager 
(link: task_1@192.168.1.62;14:55:57) 07/02/2013  21:00    <REP>          .ProActive_Scheduler 
(link: task_1@192.168.1.62;14:55:57) 15/01/2013  19:25    <REP>          .ssh 
(link: task_1@192.168.1.62;14:55:57) 25/11/2011  19:53    <REP>          .subversion 
(link: task_1@192.168.1.62;14:55:57) 29/06/2010  13:35    <REP>          .thumbnails 
(link: task_1@192.168.1.62;14:55:57) 15/06/2012  23:50    <REP>          .tidbit.d 
(link: task_1@192.168.1.62;14:55:57) 21/03/2013  20:18    <REP>          .VirtualBox 
(link: task_1@192.168.1.62;14:55:57) 25/10/2012  11:36            84y731 2012-10-25-09-36-03.095-VirtualBox.exe-4840.log 
(link: task_1@192.168.1.62;14:55:57) 23/03/2012  10:44    <REP>          AppData 
(link: task_1@192.168.1.62;14:55:57) 08/04/2013  19:00    <REP>          Bureau 
(link: task_1@192.168.1.62;14:55:57) 30/01/2009  12:34                25 configuration.ini 
(link: task_1@192.168.1.62;14:55:57) 03/02/2011  15:33             4y700 CSSite.properties 
(link: task_1@192.168.1.62;14:55:57) 13/03/2009  11:50             2y552 default.mc 
(link: task_1@192.168.1.62;14:55:57) 27/09/2010  14:24               304 default.xml 
(link: task_1@192.168.1.62;14:55:57) 11/10/2012  17:17    <REP>          dwhelper 
(link: task_1@192.168.1.62;14:55:57) 17/06/2010  16:20    <REP>          Favoris 
(link: task_1@192.168.1.62;14:55:57) 24/09/2009  13:54             1y473 gsview32.ini 
(link: task_1@192.168.1.62;14:55:57) 03/01/2013  11:02    <REP>          Menu D,marrer 
(link: task_1@192.168.1.62;14:55:57) 20/03/2013  19:26    <REP>          Mes documents 
(link: task_1@192.168.1.62;14:55:57) 16/02/2013  21:10    <REP>          origin 
(link: task_1@192.168.1.62;14:55:57) 25/11/2011  19:50               600 PUTTY.RND 
(link: task_1@192.168.1.62;14:55:57) 13/01/2011  19:00    <REP>          Snapshots 
(link: task_1@192.168.1.62;14:55:57) 20/03/2013  19:27    <REP>          VirtualBox VMs 
(link: task_1@192.168.1.62;14:55:57) 01/06/2012  19:56    <REP>          visualparadigm 
(link: task_1@192.168.1.62;14:55:57) 25/11/2008  16:58    <REP>          WINDOWS 
(link: task_1@192.168.1.62;14:55:57) 11/03/2013  18:05    <REP>          workspace 
(link: task_1@192.168.1.62;14:55:57) 20/01/2012  18:59             9y116 _viminfo 
(link: task_1@192.168.1.62;14:55:57)               13 fichier(s)          105y117 octets 
(link: task_1@192.168.1.62;14:55:57)               29 R,p(s)     917y118y976 octets libres 

In the 1.3.2 rest portal the job output is:
(link: task_1@192.168.1.62;14:55:57) Le volume dans le lecteur C n'a pas de nom. (link: task_1@192.168.1.62;14:55:57) Le numro de srie du volume est CC77-C44D (link: task_1@192.168.1.62;14:55:57) Rpertoire de C:\Documents and Settings\user (link: task_1@192.168.1.62;14:55:57) 08/04/2013 16:18 . (link: task_1@192.168.1.62;14:55:57) 08/04/2013 16:18 .. (link: task_1@192.168.1.62;14:55:57) 31/05/2012 17:06 .argouml (link: task_1@192.168.1.62;14:55:57) 20/10/2010 16:46 126 .bash_history (link: task_1@192.168.1.62;14:55:57) 01/02/2013 19:58 1110 .codesigner.cfg (link: task_1@192.168.1.62;14:55:57) 12/11/2012 01:00 20 .erlang.cookie (link: task_1@192.168.1.62;14:55:57) 31/07/2012 19:45 185 .gitconfig (link: task_1@192.168.1.62;14:55:57) 28/11/2012 16:01 .IntelliJIdea11 (link: task_1@192.168.1.62;14:55:57) 20/11/2012 17:17 .jruby (link: task_1@192.168.1.62;14:55:57) 17/06/2010 13:57 175 .location_of_StrapAlign.ini (link: task_1@192.168.1.62;14:55:57) 08/11/2012 16:52 .nbi (link: task_1@192.168.1.62;14:55:57) 31/08/2012 14:04 .nbprofiler (link: task_1@192.168.1.62;14:55:57) 16/10/2012 16:33 .netbeans (link: task_1@192.168.1.62;14:55:57) 04/03/2013 18:13 .nxshell (link: task_1@192.168.1.62;14:55:57) 11/04/2013 12:19 .proactive (link: task_1@192.168.1.62;14:55:57) 07/02/2013 20:25 .ProActive_ResourceManager (link: task_1@192.168.1.62;14:55:57) 07/02/2013 21:00 .ProActive_Scheduler (link: task_1@192.168.1.62;14:55:57) 15/01/2013 19:25 .ssh (link: task_1@192.168.1.62;14:55:57) 25/11/2011 19:53 .subversion (link: task_1@192.168.1.62;14:55:57) 29/06/2010 13:35 .thumbnails (link: task_1@192.168.1.62;14:55:57) 15/06/2012 23:50 .tidbit.d (link: task_1@192.168.1.62;14:55:57) 21/03/2013 20:18 .VirtualBox (link: task_1@192.168.1.62;14:55:57) 25/10/2012 11:36 84731 2012-10-25-09-36-03.095-VirtualBox.exe-4840.log (link: task_1@192.168.1.62;14:55:57) 23/03/2012 10:44 AppData (link: task_1@192.168.1.62;14:55:57) 08/04/2013 19:00 Bureau (link: task_1@192.168.1.62;14:55:57) 30/01/2009 12:34 25 configuration.ini (link: task_1@192.168.1.62;14:55:57) 03/02/2011 15:33 4700 CSSite.properties (link: task_1@192.168.1.62;14:55:57) 13/03/2009 11:50 2552 default.mc (link: task_1@192.168.1.62;14:55:57) 27/09/2010 14:24 304 default.xml (link: task_1@192.168.1.62;14:55:57) 11/10/2012 17:17 dwhelper (link: task_1@192.168.1.62;14:55:57) 17/06/2010 16:20 Favoris (link: task_1@192.168.1.62;14:55:57) 24/09/2009 13:54 1473 gsview32.ini (link: task_1@192.168.1.62;14:55:57) 03/01/2013 11:02 Menu Dmarrer (link: task_1@192.168.1.62;14:55:57) 20/03/2013 19:26 Mes documents (link: task_1@192.168.1.62;14:55:57) 16/02/2013 21:10 origin (link: task_1@192.168.1.62;14:55:57) 25/11/2011 19:50 600 PUTTY.RND (link: task_1@192.168.1.62;14:55:57) 13/01/2011 19:00 Snapshots (link: task_1@192.168.1.62;14:55:57) 20/03/2013 19:27 VirtualBox VMs (link: task_1@192.168.1.62;14:55:57) 01/06/2012 19:56 visualparadigm (link: task_1@192.168.1.62;14:55:57) 25/11/2008 16:58 WINDOWS (link: task_1@192.168.1.62;14:55:57) 11/03/2013 18:05 workspace (link: task_1@192.168.1.62;14:55:57) 20/01/2012 18:59 9116 _viminfo (link: task_1@192.168.1.62;14:55:57) 13 fichier(s) 105117 octets (link: task_1@192.168.1.62;14:55:57) 29 Rp(s) 917118976 octets libres

**Comment by mbenguig** [comment]
The issue still exists in 13.1.0 in the scheduler portal and the automation portal. Can be reproduced using "cmd.exe /c dir" from a native task, bash task, powershell task.
![image](https://github.com/ow2-proactive/scheduling/assets/13152450/acf147a2-0308-4b9e-9d50-497c4c5e0384)

**Comment by mbenguig** [comment]
By default, thanks to the fix, the windows cmd task switch to UTF-8 enconding by including as first instruction
`chcp 65001 >nul`.
Unfortunately it is difficult to resolve on native tasks.
