### ISSUE TITLE
Run Scheduler as a Windows Service

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1644]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1859" title="SCHEDULING-1859">Original issue</a> created by <a href="mailto:youri.bonnaffe_AT_activeeon.com">Youri Bonnaffe</a> on 17, Jul 2013 at 16:25 PM - SCHEDULING-1859

<hr />

We should at least document how to run the Scheduler and RM as a Windows service, even better create scripts or packaging to automate this.

**Comment by mbenguig** [comment]
outdated.
