### ISSUE TITLE
Inconsistent interpretation of pa.rm.select.script.timeout

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1688]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1904" title="SCHEDULING-1904">Original issue</a> created by <a href="mailto:sergei.dolgov_AT_activeeon.com">Sergei Dolgov</a> on 02, Sep 2013 at 17:06 PM - SCHEDULING-1904

<hr />

pa.rm.select.script.timeout is interpreted differently depending on whether or not the topology is used.

if it is, then pa.rm.select.script.timeout is effectively a timeout for the RMCore.getNodes() call.

If it is not, then, depending on the total number of nodes and the results of the script, RMCore.getNodes() might take much longer. The reason is that in this case SelectionManager.runScripts() is called in a loop, and the pa.rm.select.script.timeout is effectively applied to each call. Total number of calls can be up to

   (link: total number of nodes) / pa.rm.selection.maxthreadnumber

On PACAGrid for example, this makes worst-case RMCore.getNodes() take 8 minutes if pa.rm.select.script.timeout is 30 seconds.

**Comment by mbenguig** [comment]
Out-dated issue not matching with the current release.
