### ISSUE TITLE
SmartProxy default user push and pull url uses local file url instead of remote one

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1709]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1929" title="SCHEDULING-1929">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 13, Nov 2013 at 09:59 AM - SCHEDULING-1929

<hr />

During the submit, if the url is not specified, it uses the first element of the list returned by method getUserSpaceURIs(), which is the file url.

This url may not be accessible remotely

**Comment by fviale** [comment]
Using the REST SmartProxy, the file is handled by http transfer
