### ISSUE TITLE
Add automatic report submission on failure

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1757]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1983" title="SCHEDULING-1983">Original issue</a> created by <a href="mailto:vladimir.bodnartchouk_AT_activeeon.com">Vladimir Bodnartchouk</a> on 18, Feb 2014 at 18:08 PM - SCHEDULING-1983

<hr />

The start-server.js is able to detect a non-user triggerred (not with CTRL+C or 'exit') process exit of the scheduler or rm, it can then zip the contents of the .logs dir and send them to an http service running on activeeon website.

**Comment by fviale** [comment]
Won't fix as start-server.js is not used any more
