### ISSUE TITLE
Task Kill : handle TaskLauncher interruption failure

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#1767]
<a href="https://jira.activeeon.com/browse/SCHEDULING-1993" title="SCHEDULING-1993">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 10, Mar 2014 at 15:44 PM - SCHEDULING-1993

<hr />

The user code might or might not react to Thread.interrupt signals
Additionally when a task is killed during a file transfer, it will not be "interrupt-able"

There should be a configurable behavior, what to do when the interruption failed ? 

In case of agents for example, it would be reasonable to kill the node process and let the agent restart it.

**Comment by fviale** [comment]
Task interruption is only available in fork-mode.
