### ISSUE TITLE
 Make module names consistent

### ISSUE THREAD

**Issue by youribonnaffe** [ow2-proactive/scheduling#2253]
Extracted this improvement from #2251 

  - [ ] Make module names consistent
    - [ ] Put `common-api` and `common-client` in a `common` module
    - [ ] Rename module `smartproxy` and `smartproxy-common` to add `scheduler-` prefix

**Comment by lpellegr** [comment]
Resolved by https://github.com/ow2-proactive/scheduling/pull/2329.
