### ISSUE TITLE
Replace Derby by H2 or HSQLDB

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2269]
Derby is one of these *%$! databases that does not support [MVCC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control) at least in the version we are currently using.

Below a link to an issue created in 2010 that raises this point:
https://issues.apache.org/jira/browse/DERBY-4823

MVCC allows read and write transactions to be isolated from each other without any need for locking. It seems that MVCC is planned for 11.0.0.0 version but I have no idea when it will be released. 

I think that using an embedded file based database that supports MVCC could also help for #2265. I suggest to have a look at H2.

Besides, it seems that H2 has also better starting times than Derby:
http://www.h2database.com/html/performance.html

**Comment by lpellegr** [comment]
H2 also features compression for LOB:

http://www.h2database.com/html/grammar.html#set_compress_lob

**Comment by lpellegr** [comment]
I performed a few tests and using H2 with its MVStore that uses MVCC seems to solve the issue identified #2265 without having to synchronize methods in SchedulerDbManager.

Besides, using H2 instead of Derby seems to improve execution time even if H2 is configured to persist data in files. For example, SchedulerDbManagerConcurrencyTest was taking more than 14 seconds with Derby but only 6 seconds with H2.

**Comment by lpellegr** [comment]
Two options should be investigated, respectively for compression but also compaction:

  - `COMPRESS=TRUE`
  -  [` MAX_COMPACT_TIME=500`](http://www.h2database.com/javadoc/org/h2/constant/DbSettings.html)

**Comment by lpellegr** [comment]
Option `DB_CLOSE_DELAY=-1` is required with in-memory mode in order to prevent data loss when the last connection to a database closes the database.

**Comment by lpellegr** [comment]
I have discovered, with some tests that kill the scheduler abruptly, that once the database is reopened some data (especially LOBs) are sometimes corrupted. My investigations on the H2 mailing list suggest this is a known issue. Consequently, I think H2 in version 1.4 with MVCC enabled is not yet stable enough to be used.

I have started to look at HSQLDB which supports MVCC too and seems more stable than H2.

**Comment by fviale** [comment]
What is the state of this issue ? Did you make some tests with HSQLDB ?

**Comment by lpellegr** [comment]
Using HSQLDB with MVCC engine seems to solve all deadlock issues that were encountered. The task was part of bigger "upgrade dependencies" Epic. Since it was not the priority, nobody had time to continue the work which was started to include it with the master.

As Brian said yesterday, it is planned for 7.0 to freeze the current upgrades, test and merge them with the master if we have time. They are still a few tests tests failing (~4) when they are run consecutively. Maybe it is related to the change with the database but not sure.

Updates related to the "upgrade dependencies" are currently in my fork:

https://github.com/lpellegr/scheduling/commits/bump-dependencies

**Comment by fviale** [comment]
thanks for the update
