### ISSUE TITLE
Improve NODE_ACCESS_TOKEN

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2275]
Property `-Dproactive.node.access.token` allows to define to a tag per ProActive node. This way, a user can define on which node with which tag a task must be executed by defining `NODE_ACCESS_TOKEN=X` in the generic information section of a task.

This manner to proceed is a really convenient manner for users to select a specific set of nodes for execution (e.g. Enterome and OpenOcean use case). Unfortunately, the implementation has currently some drawbacks:
- Suppose that all ProActive nodes have a tag defined with '-Dproactive.node.access.token', if 'NODE_ACCESS_TOKEN' is not defined, then the job remains in pending state
- 'NODE_ACCESS_TOKEN' is ignored if defined in generic information at the job level. This is really annoying for jobs with a lot of tasks.

Some new interesting features could also be added:
- Support for a list of tags per ProActive node
- Support for dynamic addition/removal of tags

The idea is not to replace selection scripts that are more powerful, but to provide a convenient manner for users to select nodes based on non-dynamic properties without having to write code.

**Comment by youribonnaffe** [comment]
Jenkins and Kubernetes use labels for node selection, it might be interesting to look at how they do it as an inspiration.

**Comment by fviale** [comment]
This improvement should be considered major as it would improve a lot node selection

**Comment by fviale** [comment]
> Suppose that all ProActive nodes have a tag defined with '-Dproactive.node.access.token', if 'NODE_ACCESS_TOKEN' is not defined, then the job remains in pending state

This is the expected behavior. No change needed here.

> 'NODE_ACCESS_TOKEN' is ignored if defined in generic information at the job level. This is really annoying for jobs with a lot of tasks.

Not true any more since many versions.

> Support for a list of tags per ProActive node
> Support for dynamic addition/removal of tags

A separated feature called node tags have been implemented
