### ISSUE TITLE
Using files for selection scripts in studio (also task scripts)

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2278]
Currently, it is required to copy and paste the content of a selection script that has to be used on multiple tasks. It would be really convenient to have the possibility to reference a file that contains the code of a selection script (e.g. Enterome use case).

**Comment by fviale** [comment]
:+100:
There used to be a script library mechanism in the studio. The feature has been removed for obscure reasons, and now the need appears again ...

**Comment by fviale** [comment]
this is a studio issue, replaced by https://github.com/ow2-proactive/studio/issues/472
