### ISSUE TITLE
Remove tools/proactive-server-script

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2285]
This script should no longer be used. Besides, it leads to confusion.

Related files should also be removed, such as `tools/startup.groovy`.

**Comment by fviale** [comment]
This script was done to allow (via the startup.groovy script), to easily customize the starting of the scheduler. It seems that since then we never had the need to use it. Instead of removing them, we could alternatively put them under tools/legacy to avoid confusion.
