### ISSUE TITLE
nashorn cast exception when creating a node with the Command Line 

### ISSUE THREAD

**Issue by marcocast** [ow2-proactive/scheduling#2286]
Adding a new node source in Interactive mode with the command line, throws the following exception : 
```
createns( 'moreLocalNodes', ['org.ow2.proactive.resourcemanager.nodesource.infrastructure.LocalInfrastructure', './config/authentication/rm.cred', 4, 60000, ''], ['org.ow2.proactive.resourcemanager.nodesource.policy.StaticPolicy', 'ALL', 'ALL'])

', 'ALL'])

An error occurred.

Error Message: Cannot cast jdk.nashorn.api.scripting.ScriptObjectMirror to [Ljava.lang.String;
```
This is related to a JDK bug : https://bugs.openjdk.java.net/browse/JDK-8072596

**Comment by lpellegr** [comment]
Java 8u60 is [planned before September](http://openjdk.java.net/projects/jdk8u/releases/8u60.html). Consequently, the new JRE can probably be included with the distribution for the next release.

**Comment by lpellegr** [comment]
JRE version [upgraded to 8u60](https://bitbucket.org/activeeon/release/commits/940d3432b203336fe5a73b9cbfc2d315ac410e3b).
