### ISSUE TITLE
proactive-client option -r or --removens is broken

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2344]
When trying to use the -r option on proactive-client, the following message appear:
```
H:\Users\fviale\Documents\GitHub\scheduling\bin>proactive-client -r toto

Missing argument for option: r

Error message: Missing argument for option: r

You can enable debug mode for getting more information using -X or --debug option.
(...)
```

**Comment by lpellegr** [comment]
Maybe fixed by https://github.com/ow2-proactive/scheduling/pull/2335. Should be checked once merged.

**Comment by lpellegr** [comment]
Fixed by https://github.com/ow2-proactive/scheduling/pull/2335.
