### ISSUE TITLE
Investigate REST throughput limitation

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2350]
While running micro-benchmarks on EC2 it was noticed that ProActive server is never using more than 2 cores for handling REST calls even if more are available. In that case, a machine having an _Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz_ has a maximum throughput of _15_ submits handled per second.

Increasing number of machines used to submit workflows but also the number of proactive-client per machine (up to _2_ hosts and _4_ clients per host) has no effect. This suggests the issue is on the server side.

It could be interesting to check if this limitation is due to some contention to write new jobs in the database (or synchronization on some other data structures) or if the limitation is due to bad Jetty or Resteasy configuration.

The workflow used for the submission was the one below:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<job
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:proactive:jobdescriptor:3.3"
     xsi:schemaLocation="urn:proactive:jobdescriptor:3.3 http://www.activeeon.com/public_content/schemas/proactive/jobdescriptor/3.3/schedulerjob.xsd"
    name="Hello from Java"
    priority="normal"
    cancelJobOnError="false">
  <taskFlow>
    <task name="Java"
    maxNumberOfExecution="4">
      <javaExecutable class="HelloWorld"></javaExecutable>
      <controlFlow block="none"></controlFlow>
    </task>
  </taskFlow>
</job>
```

**Comment by fviale** [comment]
Contention on the rest api and job submission has been analysed.

Job submission contention resides within the database, when the new job need to be saved.

Several minor improvements (such as using cache, and maximize parallelization) have been made.
