### ISSUE TITLE
Allow scheduler to have jobs that are not scheduled for execution on startup

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2356]
While running benchmarks it was noticed that submission may be slow to submit a bunch of jobs. It means that if submitting _X_  jobs takes _Y_ time units, then each benchmark _run_ requires Y time units to insert jobs. Thus if _Z_ runs are required _Y \* Z_ times units are required.

We were thinking to take a snapshot of a Scheduler instance having already all required Jobs inside (persisted in `data` folder) and reuse it for next runs, so that only _Y_ time units are required. However, this requires that once the Scheduler is restarted, Jobs are not scheduled immediately if some nodes are available or added.

At least 3 solutions are possible to achieve this goal:

   1) Add an option to allow to pause the scheduling loop of the scheduler
   2) Add the possibility to add nodes in a pre-defined state (locked) 
   3) Allow to submit jobs in a pre-defined state (e.g. paused)

I think option _3_ (along with option 2 maybe) is the most easier to implement and probably the one that can be useful for others scenarios.

**Comment by tobwiens** [comment]
I like the idea of giving the state of a job, optionally.

**Comment by lpellegr** [comment]
Option 2 has been implemented with https://github.com/ow2-proactive/scheduling/pull/2784. It can be considered as fixed.
