### ISSUE TITLE
Fork mode should be overridable at a task level

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2365]
Currently, the default Fork Mode is defined at a server level only. This allows the scheduler admin to decide the way the Nodes handles tasks.

But this configuration may not work for every scenario, what if a given task requires absolutely a fork and fork mode is deactivated ? Or the opposite ?

**Comment by lpellegr** [comment]
:100:

**Comment by lpellegr** [comment]
If we provide this at task-level,
we need as well to have a mechanism to enforce fork-mode defined by admin.

**Comment by fviale** [comment]
It is now possible to override fork mode at task level.
