### ISSUE TITLE
Augment default PNP heartbeats

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2367]
PNP protocol default heartbeat time is very low (9 seconds).

In a lot of cases, this implies unnecessary disconnection problems.

Even though it's configurable, default values are important. Here I would recommend a default of 60 seconds. 

This change could be done either:
- in the network/node.ini and network/server.ini config files for PWS packages and Agents
- directly in the PNP protocol config class.

**Comment by paraita** [comment]
:+1: do you think that could help fix #1986 ?

**Comment by fviale** [comment]
#1986 is a different matter. The purpose of augmenting heartbeat period is to reduce unwanted disconnections, not supress them completely (it's impossible as real disconnections can occur).

I put a comment on #1986 as for me this is only a problem of configuration.

**Comment by fviale** [comment]
merged.
