### ISSUE TITLE
Disable topology distance computation by default

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2373]
As observed in #2359, Node registration takes too much time when there are many Nodes.

The topology computation at node registration is the main reason why it is so long.

Accordingly, and as the feature has never been used so far (for multi-node execution, we mostly rely on  other settings), I propose to disable the topology by default.

**Comment by lpellegr** [comment]
:100: 

However, I think that the scheduler should be able to enable it automatically if a submit with topology parameters is submitted. Otherwise, a user may think the feature is not working whereas it's just a matter of configuration.

**Comment by fviale** [comment]
Looking at the code, it is unclear if by disabling the topology, the selection mechanism will work properly. Exceptions are thrown and not seem to be catched, etc. We should try to disable it and manually test that selection scripts and multi-node execution with other setting work. As @lpellegr notes, we should also check that a proper error message is forwarded to the client when it is disabled.

**Comment by fviale** [comment]
@lpellegr, automatic enabling of the topology at workflow submission seems difficult to implement. I'd rather forward a proper error message.

**Comment by fviale** [comment]
EDIT: following customer tests with topology disabled, it seems other kind of Multi-Node selection are not working properly when topology is off.
