### ISSUE TITLE
Provide scripts inside the "tools" folders to install the scheduler as a service (linux only)

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2425]
It can be:

1) on linux, a bash script install.sh which copies a generic "proactive-scheduler" startup script to /etc/init.d and then use chkconfig to install it on startup (with some adaptations for different distributions redhat, debian) 
2) on windows, a bat script calling the command SC.exe could be interesting, but this would be for later
https://support.microsoft.com/en-us/kb/251192

This is a very helpful feature when we install the scheduler in production

**Comment by lpellegr** [comment]
+:100: 

For Linux systems it would be nice to have a systemd script since systemv scripts tend to be deprecated.

It seems to be a duplicate of the existing issue #2015.

**Comment by paraita** [comment]
upstart script too ? (Ubuntu)

**Comment by lpellegr** [comment]
@paraita Good idea, although systemd is now supported since 15.04 but not yet in LTS version apparently:

https://wiki.ubuntu.com/SystemdForUpstartUsers

**Comment by fviale** [comment]
install.sh and uninstall.sh scripts added in the tools folder.
