### ISSUE TITLE
Add variables bindings to selection script execution

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2428]
Currently, it is not possible to access job variables from selection script, only pattern replacement with ${variable_name} is done in the code itself.

**Comment by lpellegr** [comment]
https://trello.com/c/kRqUPCsB

**Comment by lpellegr** [comment]
> It should take one week of work max. the idea is to add variable bindings to the Criteria class (to avoid cascade API changes), and then add a method executeScript(Script<T> script, Map<String, Serializable> bindings) to the RMNode interface
