### ISSUE TITLE
Add 2 logo slots on the 3 proactive web portals: ActiveEon's logo & Partner's logo.

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/scheduling#2430]
ActiveEon's logo is missing on the 3 web portals, and we have to offer a way to customize the web portals according to the customers. In a commercial point of view, the partner having purchased a "premium" version, could choose to only display its logo without the ActiveEon one.

**Comment by fviale** [comment]
Log-in/Log-out button on the right side has been done for release 7.4.0. The rest of the feature will be added on 7.5.0

**Comment by fviale** [comment]
feature implemented and merged in 7.5.0
