### ISSUE TITLE
Embedded Jetty registers default and basic error handler

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2461]
Usually, Web services developed with recent libraries (e.g. Spring) provide advanced error handlers that allow to get an error in a structured way along with the required information to understand the cause.

For instance, when the workflow-catalog is run in standalone mode, if an error occurs due to a syntax error with a search, the following JSON error is returned:

```
{
  "timestamp": 1455203381233,
  "status": 400,
  "error": "Bad Request",
  "exception": "org.ow2.proactive.workflow_catalog.rest.query.QueryPredicateBuilderException",
  "message": "<unknown>: line 1:14 token recognition error at: '<'\n<unknown>: line 1:15 token recognition error at: '>'\n<unknown>: line 1:17 missing COMPARE_OPERATOR at '\"test\"'",
  "path": "/buckets/1/workflows"
}
```

Now, the same service (workflow-catalog) deployed on the embedded Jetty container, and by executing the same requests, returns only the HTTP status:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400</h2>
<p>Problem accessing /workflow-catalog/buckets/1/workflows. Reason:
<pre>    Bad Request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

By default, Jetty registers its own basic error handler. However, this looks configurable.

The issue applies to all Web services (especially RESTful Web services) managed by the Jetty container started with the scheduler.

**Comment by fviale** [comment]
Error handling should be implemented directly in the concerned micro-service and not at jetty server level.
