### ISSUE TITLE
Replace SSHInfrastructure by SSHInfrastructureV2

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2471]
_SSHInfrastructure_ relies on Trilead SSH2 library. It makes by default several assumptions regarding SSH configuration and access (e.g. system username is the same on Scheduler and compute nodes). Besides, it forces the user to give the path to RM credentials whereas this operation could be transparent to the user. Furthermore, one bug (https://github.com/ow2-proactive/scheduling/issues/1977) that applies to this implementation only has been reported and not yet fixed.

_SSHInfrastructureV2_ resolves the previous issues. It relies on JSCH library. SSH username, port, password and path to a private key file are required by default along with the path a to an SSH configuration file to load.

Having both infrastructures is really confusing. It is reinforced by the fact that documentation is partial. I think _SSHInfrastructureV2_ could replace _SSHInfrastructure_. Indeed, the former is more flexible. 

If _SSHInfrastructure_ cannot be replaced for compatibility reasons, it should at least be marked as deprecated and documentation updated to mention _SSHInfrastructureV2_ only.

**Comment by fviale** [comment]
Rename previous SSHInfrastructure to SSHInfrastructureLegacy + SSHInfrastructureV2 to SSHInfrastructure. Documentation about new renamed SSHInfrastructure only.

**Comment by fviale** [comment]
SSHInfrastructureV2 is now preferred and used over SSHInfrastructure.

Renaming SSHInfrastructure seem not necessary
