### ISSUE TITLE
SSH infrastructures require to define a target OS parameter

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2472]
SSH infrastructures require to define a parameter named `targetOs`. This last parameter is used on Scheduler side to build the Java command that will be executed on remote machines to start ProActive nodes (mainly to use appropriate path separators). 

The main issue with this behaviour is that all machines attached to a node source deployed with an SSH infrastructure are necessarily running the same OS family (i.e either Linux or Windows). Similarly, it looks like the host file passed as parameter must have all mentioned IPs that refer to machines that run the same OS family. I haven't found documentation regarding this last point. 

It seems possible to deduce the value for `targetOs` automatically by executing a command by SSH, as first step, to detect remote node OS. Also, this detection could be applied per remote node. This way to proceed would fix the previous issues and make SSH infrastructures simpler to use by removing parameter `targetOS`.

**Comment by fviale** [comment]
Node sources (apart from the Default node source) are supposed to be as uniform as possible. All nodes acquired from the same node source will share the same JVM properties, the same java path, the same proactive installation path. I don't see how this could work when nodes are running on different platforms linux/windows. Obviously all the file system paths would be different.

In case Nodes must be acquired using SSH from different operating systems, creating separate node sources is the rule.

**Comment by lpellegr** [comment]
@fviale Ok, right, my proposition is really stupid. I was confused by the documentation of the Hosts List parameter.  It would be nice to clearly state what you explained in the documentation.

**Comment by fviale** [comment]
It can be part of the work on #2471: use only one SSH infrastructure, and clarify the documentation
