### ISSUE TITLE
how to run a cron job with Automatic update date parameter?

### ISSUE THREAD

**Issue by tingking23** [ow2-proactive/scheduling#2474]
how to run a cron job like "xxx.sh 2016-02-01" ?

the parameter "2016-02-01", i want it to changed automatic according to the system time.

i can't find this function in the proactive, could you help me?

**Comment by paraita** [comment]
Hi @tingking23 
If you are using a Linux Bash Task to call xxx.sh, you can use the `date` command:
```date +%Y-%m-%d```
You can have a look at the [cron tasks documentation](https://doc.activeeon.com/latest/user/ProActiveUserGuide.html#_cron_tasks) if you need cron functionalities.

**Comment by tingking23** [comment]
@paraita 
i do it like this take it ok. with bash script sh test.sh `date +%Y-%m-%d` not execute with native command
thank you very much! 
if you can put a demo like this in the document is perfect.
