### ISSUE TITLE
Cannot identify task state from a clean script

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2476]
A clean script is executed after a task execution, even if the latter has failed.

Unfortunately, it looks impossible to identify if the clean script has been executed after a task failure or a task success. I have checked environment variables and Java properties from the context of a clean script. We don't have this information, neither the Job or the Task ID in order to make a call to the REST API.

Offering the possibility to differentiate between both (by giving for instance access to the exitCode of the task to the clean script) will allow us to execute a piece of code after a task execution and only if the task has failed, which is currently not possible.

Giving access to the Job and Task ID looks also required to be able to interact with the REST API.

**Comment by bamedro** [comment]
post-script is supposed to put this information in the script context, but after a few tests, it seems that it is not running after a failed tasks, even if documentation claims this opposite:

    **post-script** - the post-script is executed on the same node after the task itself in any case. A boolean variable named "success" is available in this script in order to inform user about the success of the task execution. if success is true, the execution has finished successfully, if not, execution has generated an exception. The same helpers than for pre-script can be used in the post-script, except the org.ow2.proactive.scripting.helper.PropertyUtils.exportProperty(String name) which has no effect since no process can be forked after the post-script.

   ** cleaning-script** - the cleaning-script is always executed by the Resource Manager after the execution of the task itself or after the post-script (if used). The same helper than for pre-script can be used in the cleaning-script.

**Comment by lpellegr** [comment]
@brianamedro Below is a screenshot from the Studio that describes the behaviour of the post-script:

![screen shot 2016-03-03 at 07 39 37](https://cloud.githubusercontent.com/assets/128898/13487676/9a6bcd1e-e113-11e5-9b27-f6c0d5fe5de7.png)

Consequently, I am not sure it is a bug like you said. 

Where have you found the documentation you mentioned?

**Comment by fviale** [comment]
Let's keep the current behaviour. Add env (variable bindings) to the clean script + update documentation.

**Comment by lpellegr** [comment]
Fixed by https://github.com/ow2-proactive/scheduling/pull/2569.
