### ISSUE TITLE
when i changed the web.port=8088 then the Scheduler can't login

### ISSUE THREAD

**Issue by tingking23** [ow2-proactive/scheduling#2483]
As the title ,when i set the web.port=8088 not the 8080 then i only can login the studio,the scheduler and rm web can't login with admin/admin. Is there other things need to change and i missed?

**Comment by lpellegr** [comment]
@tingking23 Yes, there are some other configuration files to update. In the release distribution you can find unpacked WAR files associated to RM and Scheduler Web apps in `PROACTIVE_HOME/dist/war` folder. You need to update the following configuration files according to your web setup:

  - `dist/war/rm/rm.conf` to set `rm.rest.url=https://localhost:8088/rest`
  - `dist/war/scheduler/scheduler.conf` to set `sched.rest.url=https://localhost:8088/rest`

Please let us know whether it solves your issue or not.

**Comment by tingking23** [comment]
@lpellegr thank you very much, it works.
