### ISSUE TITLE
run the proactive on host use user A ,then the A can't to ssh to that host again

### ISSUE THREAD

**Issue by tingking23** [ow2-proactive/scheduling#2484]
befor start proactive :  use ssh login to the host with user pro
the ulimit -n is 65536 ulimit -u is 10240
the system open file was 55

after start the proactive : use ssh to login the host failed with erro "connection to host closed by remote host"
 and the system open file was 9870

ps: i only create 10 nodes and no workflow running at the proactive

**Comment by fviale** [comment]
10 nodes will create 10 JVMs with the SSHInfrastructure. 10 JVMs can use a lot of memory.
Could you type the command "free" and copy the output before you deploy on the host ?

**Comment by fviale** [comment]
not enough information is provided
