### ISSUE TITLE
Provides a workflow dependence 

### ISSUE THREAD

**Issue by leven2012** [ow2-proactive/scheduling#2511]
I need workflow dependence ,  whether to provide the related API ?

**Comment by mbenguig** [comment]
Hi leven2012, could you detail please?

**Comment by leven2012** [comment]
proactive is based on task ,now;
but i need established between workflows dependence 
For example, 
the completion of A workflow to workflow B ，But now it seems can't do this

**Comment by leven2012** [comment]
But now it seems can't do this

**Comment by leven2012** [comment]
It is based on dependencies between tasks，But I need the dependencies between is based on the workflow 
for example:
the workflow B start automatically after the completion of A workflow ，But now it seems can't do this

**Comment by mbenguig** [comment]
Why not import A & B and just add a dependency between them? Another possibility would be to delay the execution of B by setting the START_AT workflow property (generic infos menu of the workflow, then add the property START_AT and set your time following the ISO8601 format)
