### ISSUE TITLE
run computation with your system account ?

### ISSUE THREAD

**Issue by leven2012** [ow2-proactive/scheduling#2514]
i have do this:

    Using your scheduling login and password : if computing hosts are configured and user is authorized to run a process under his login and password.

    Using an SSH key provided by the administrator : if computing hosts are configured, the administrator should have given user an SSH key.

User must first create a credential containing this key :

$ PROACTIVE_HOME/tools/proactive-create-cred -F config/authentication/keys/pub.key -l username -p userpwd -k path/to/private/sshkey -o myCredentials.cred

but task is running，have no any excepiton**

**Comment by mbenguig** [comment]
Hi leven2012, coud you please detail?

**Comment by mbenguig** [comment]
Hi leven, thank you for your implication.. but I will close this issue if you do not give us more details.
