### ISSUE TITLE
Resource providers have the same permissions as users + an ability to add remove node

### ISSUE THREAD

**Issue by leven2012** [ow2-proactive/scheduling#2515]
i try use a provider to login scheduler or  rm.but fail; 
Do not have permission

**Comment by mbenguig** [comment]
Hi leven2012, coud you please detail?

**Comment by mbenguig** [comment]
Hi leven, thank you for your implication.. but I will close this issue if you do not give us more details.

**Comment by fviale** [comment]
Hello Leven2012, your issue title does not describe an issue, it's only a statement. So it's difficult for us to understand clearly the problem. 

The accounts belonging to the category "providers" have very limited rights. They are described inside the following file:

https://github.com/ow2-proactive/scheduling/blob/master/config/security.java.policy-server

Under the line:
```
grant principal org.ow2.proactive.authentication.principals.GroupNamePrincipal "providers" 
```
They don't have the same rights as users, they cannot interact at all with the scheduler (listing or submitting jobs, etc). 

They can only add nodes to an existing Node Source (which is not allowed to users).

If an account needs to be able to interact with the scheduler AND add nodes, it needs to be a member of users AND providers.
