### ISSUE TITLE
Is there something wrong with the constructor JobInfoImpl?

### ISSUE THREAD

**Issue by leven2012** [ow2-proactive/scheduling#2519]
numberOfFailedTasks、numberOfFaultyTasks、numberOfInErrorTasks, etc.
Didn't pass the following Settings 
  this.numberOfFailedTasks = jobInfo.getNumberOfFailedTasks();
  this.numberOfFaultyTasks = jobInfo.getNumberOfFaultyTasks();
  this.numberOfInErrorTasks = jobInfo.getNumberOfInErrorTasks();
Cause I can't get the value later by JobInfoImpl

**Comment by tobwiens** [comment]
Hi leven2012,

Can you point to the piece of code. (http://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github). 

Can you give more details about what you are trying to achieve, Can you post your piece of code here.

Cheers,
Tobias

**Comment by leven2012** [comment]
jobStateUpdated method will  update jobsMap's jobstate by JobInfo, then send email, I hope get the numberOfFailedTasks,numberOfFaultyTasks,numberOfInErrorTasks; but because this jobInfo is not Initialized in the constructor
for example:
 1、       if (jobFinished) {
            //send event to client
            listener.jobStateUpdated(job.getOwner(), new NotificationData<JobInfo>(
                    SchedulerEvent.JOB_RUNNING_TO_FINISHED, new JobInfoImpl((JobInfoImpl) job.getJobInfo())));
            loopSendEmail = false;
        }
２、jobStateUpdated
JobState js = jobsMap.get(notification.getData().getJobId());
        js.update(notification.getData());

cat't update js(jobstate)

**Comment by tobwiens** [comment]
You can access the REST API and get all information about a job. 

Can you post some of your code and point to the constructor which you are talking about. (http://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github)

**Comment by leven2012** [comment]
HTTP ERROR 404

Problem accessing /scheduler/jobs/102/log/server/. Reason:

    Not Found

Powered by Jetty://

I didn't hope need to login in order to get this infomation（job info,job log,etc.）,but the rest api must need login status

**Comment by tobwiens** [comment]
It highly depends on what you are trying to do. 

Usually all interactions are done through the REST interface, that is what the API is designed for. 
Here is the documentation of the REST API: https://try.activeeon.com/rest/doc/
