### ISSUE TITLE
When accessing files in user/global space from the rest api, a desynchronization can occur 

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2527]
This issue appeared randomly in long sequence of jobs using dataspaces.

At the job termination, the file was requested from the REST API but could not be found, even though it was on the file system.

It seems to be an issue with VFS cache mechanism. Explicit re-synchronization should be used whenever possible.

**Comment by lpellegr** [comment]
@fviale Is it fixed by your last two commits?

**Comment by fviale** [comment]
I cannot say as the patch has not been yet applied at CEA

**Comment by fviale** [comment]
it seems fixed as no more incident as been reported since several months
