### ISSUE TITLE
In Error and Paused state can switch to Stalled

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/scheduling#2529]
In line 292 in InternalJob, we seem to want to prevent a job going into the STALLED state if it is PAUSED or In Error:
[Link](https://github.com/ow2-proactive/scheduling/blob/master/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/job/InternalJob.java#L292).

But a Job can enter the stalled state, because this evaluates to true: 
(getStatus() != JobStatus.PAUSED || getStatus() != JobStatus.IN_ERROR)

**Comment by lpellegr** [comment]
:+1:
