### ISSUE TITLE
Add variables bindings and genericInformation to selection scripts

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling#2565]
Currently selection scripts contain no binding. It is though useful to access up-to-date job variables, "generic information" and standard info like job name, task id, etc.

**Comment by lpellegr** [comment]
@fviale Why are you creating an issue when you provide a pull-request for this issue on the same day? on Github, issues and pull-requests share the same sequence ID. If you use the search field from the "Issues" tab without specific filter you will see that Issues and Pull-requests are displayed:

https://github.com/ow2-proactive/scheduling/issues?utf8=%E2%9C%93&q=is%3Aopen+
