### ISSUE TITLE
File based authentication does not support any character

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2601]
It is not possible to use any character in passwords defined in `login.cfg`. Alphanumeric characters and some ASCII characters work but not all. 

A simple way to reproduce the issue is to add the following entry to `login.cfg` and try to authenticate to one of our Web portal using these credentials:

```
coucou:raté
```

**Comment by fviale** [comment]
Indeed, I met a similar issue earlier:
https://github.com/ow2-proactive/scheduling/issues/1994


On Wed, Jul 6, 2016 at 3:43 PM, Laurent Pellegrino <notifications@github.com

**Comment by lpellegr** [comment]
Related to https://bitbucket.org/activeeon/activeeon-website/issues/34/users-can-register-with-password-not

**Comment by lpellegr** [comment]
I made some tests and I noticed the issue is fixed.
