### ISSUE TITLE
log4j:WARN No appenders could be found for logger (org.python.netty.util.internal.logging.InternalLoggerFactory)

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2606]
Reproducing the issue requires that a Scheduler with no local node is up and running and that some ProActive nodes are attached to the ProActive Scheduler using ProActive agents (Windows or Linux).   

Then, if you create and execute a simple Python task that imports _urllib2_, you will get the following output:

```
[252t0@172.30.0.146;07:40:29] log4j:WARN No appenders could be found for logger (org.python.netty.util.internal.logging.InternalLoggerFactory). 
[252t0@172.30.0.146;07:40:29] log4j:WARN Please initialize the log4j system properly. 
[252t0@172.30.0.146;07:40:29] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info. 
```

I have tried to configure _node.properties_ logger and to pass "-Dlog4.configuration=file:..." as JVM parameter. Both solutions are not working. The only one I have found is to configure the Scheduler to use non forked tasks on nodes. As a consequence, it looks like some Log4j properties are not forwarded to the JVM that is forked and used to execute the task. Or, since the issue occurs only with agents, maybe the path to the log4j configuration path is not correct.

Issue was reported from a _customer_.

**Comment by fviale** [comment]
fixed by f02bd60
