### ISSUE TITLE
Race Conditions Party in HostsFileBasedInfrastructureManager

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling#2811]
The current implementation of `HostsFileBasedInfrastructureManager` makes use of multiple maps. Some could most probably be avoided by using appropriate data structures. Furthermore, under several circumstances (e.g. a user who remove a node while in parallel another Thread detects the same node as down and trigger a removal, node reconnections, etc.) race conditions may happen. 

All the logic and data structures keeping track of the needed information should be extracted into a dedicated class, thus simplifying synchronization, testing, and maintenance.

**Comment by fviale** [comment]
fixed by recent changes in HostsFileBasedInfrastructureManager
