### ISSUE TITLE
SchedulerLoadingPolicies scale up only one time, then can only scale down

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling#2820]
SchedulerLoadingPolicy should be able, continuously to scale up or down, according to the settings provided at its creation time.

To reproduce:
1. Create a new NS with LocalInfra + SchedulerLoadingPolicy
2. NS Infra: Up to 10 nodes for the LocalInfra
3. NS Policy: Max 10 nodes, min 0 nodes, Factor: 1 task per node
4. Submit a job with 10 tasks all depending on a first single task

**Comment by fviale** [comment]
fixed by https://github.com/ow2-proactive/scheduling/commit/80ed7791eb3b16a7ff682f16b1e249c09360ee08

SchedulerLoadingPolicy was moved to a separate project
