### ISSUE TITLE
SchedulerLoadingPolicy should rely on Elligible Task for Execution, rather than Pending Tasks in general

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling#2821]
SchedulerLoadingPolicy should trigger a scale up according to the number of tasks which are ready for execution

To reproduce:
0. We start with proactive-server -ln 1
1. Create a new NS with LocalInfra + SchedulerLoadingPolicy
2. NS Infra: Up to 10 nodes for the LocalInfra
3. NS Policy: Max 10 nodes, min 0 nodes, Factor: 1 task per node
4. Submit a job with:
- 1 Task waiting for 60 secs --> 1 Task waiting for 60 secs ==> 4 tasks waiting for 60 secs --> 1 Task for 60 secs
5. As soon as the first task starts, the start of 6 nodes is triggered (6=1+4+1), but it should wait for the termination of the second task to trigger execution of 3 extra nodes (so the 4 can run in parallel,  as requested by the "Factor: 1 task per node")

**Comment by bamedro** [comment]
Currently, the policy is looking at the number of Pending Tasks (whatever if ready for execution or not) for each job.
We should only get the number of Tasks Ready for Execution directly from the Scheduler. No need to look at the jobs. Likely: org.ow2.proactive.scheduler.policy.Policy.getOrderedTasks()

**Comment by fviale** [comment]
fixed by https://github.com/ow2-proactive/scheduling/commit/80ed7791eb3b16a7ff682f16b1e249c09360ee08

SchedulerLoadingPolicy was moved to a separate project
