### ISSUE TITLE
Scheduler crashes after a few days of continuous job submission

### ISSUE THREAD

**Issue by paraita** [ow2-proactive/scheduling#2850]
The Scheduler is running with 4 local nodes. I submit a job every 2 seconds (one task doing nothing). Housekeeping is set to trigger every 10 minutes and remove finished jobs older than 1 hour.
Everything seems to work fine for the first 23 hours, then the jobs start to have trouble getting executed on the nodes, although the removal still work as expected. After a few more hours, the scheduler crashes. No particular error in the logs.

Database usage over time:
![image](https://cloud.githubusercontent.com/assets/1413759/25484732/79eb288a-2b5b-11e7-9e08-29e469399742.png)

**Comment by paraita** [comment]
I noticed this message appears regularly in the logs:
```
[2017-04-26 13:37:51,073 istics.rrd ERROR o.o.p.s.c.j.SchedulerJMXHelper] Bad sample time: 1493206671. Last update time was 1493206683, at least one second step is required
java.lang.IllegalArgumentException: Bad sample time: 1493206671. Last update time was 1493206683, at least one second step is required
	at org.rrd4j.core.RrdDb.store(RrdDb.java:553)
	at org.rrd4j.core.Sample.update(Sample.java:197)
	at org.ow2.proactive.jmx.RRDDataStore.run(RRDDataStore.java:181)
```

**Comment by paraita** [comment]
Nevermind, that JMX helper wasn't the cause of the issue.

**Comment by paraita** [comment]
After putting more information into the logs, we managed to fix some of the issues causing the memory growth. Now the house keeping mechanism works on both memory and DB for the jobs (see the Scheduler DB and Scheduler Memory below) but we still have the memory that grows slowly over time (notice the RAM Usage):
![image](https://cloud.githubusercontent.com/assets/1413759/26571179/cfac27f6-4514-11e7-8751-4033cbc569fa.png)

**Comment by fviale** [comment]
This is fixed together with the memory leak fixes
