### ISSUE TITLE
Connection error between scheduler/rm and remote postgresql database

### ISSUE THREAD

**Issue by gheon** [ow2-proactive/scheduling#2869]
Release: ProActiveWorkflowsScheduling-linux-x64-7.27.0.zip
Setup:  - running inside Kubernetes cluster on Azure
        - 1 pod (~ Docker container) for the scheduler (including RM & co)
        - 1 pod for the scheduler 'remote' database
          => the defaut HSQL db is not used
          => instead we setup a 'remote' postgresql db, reachable by the
            scheduler container to save its state & data

Bug:  On the scheduling portal, before executing any workflow, the statut of the
      top panel keep printing "Fetching jobs...", but there is no job at all 
      (see screenshot [1]).
      After executing a first workflow using the studio, the scheduler then
      cannot properly connect to the db to fetch or store data, and an error box
      pops up (see screenshots [2]). According to the error messages (see screenshot
      [3] and [output.txt]), it seems related to the auto-commit of large objects,
      triggering and Hibernate/PSQL exception.
      It is therefore impossible to retrieve the list of submitted jobs, and to retrieve their total 
      number  as well.
      The scheduler log file is also attached [Scheduler.txt] at the bottom of this post.
      This bug does not occur on the release 7.26.

![1](https://cloud.githubusercontent.com/assets/26597721/26300514/a13caa08-3ede-11e7-86b4-d0902915f503.png)
![2](https://cloud.githubusercontent.com/assets/26597721/26300519/a385068e-3ede-11e7-9f21-95ff9531e11f.png)
![3](https://cloud.githubusercontent.com/assets/26597721/26300524/a93544ea-3ede-11e7-92ba-ead6f62497a5.png)

[output.txt](https://github.com/ow2-proactive/scheduling/files/1018235/output.txt)
[Scheduler.txt](https://github.com/ow2-proactive/scheduling/files/1018254/Scheduler.txt)

**Comment by vinseon** [comment]
Reason: We were missing some microservices database configuration.
Problem solved by customizing appropriate  `application.properties` files inside `dist/war`.
