### ISSUE TITLE
Scheduler should not accept a job if ScriptEngine value is missing

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling#2952]
To reproduce:
1. Open Studio
2. Create a workflow with a single task
3. Select the empty line in the Language menu
4. Execute the job
==> Scheduler should reject the submission. Task will fail.

Bigger problem:
3. Add a selection script
4. Leave Language to blank
5. Set type to Dynamic or Static
6. Write something in the selection script code section (to not leave it blank)
6. Execute the job
==> Scheduler should reject the submission. Task remains pending, but the selection script is retrying continuously, producing a lot of logs in Scheduler.log (~4 MBytes / Minute)

**Comment by bamedro** [comment]
Attached file cause this issue

`<?xml version="1.0" encoding="UTF-8"?>
<job
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:proactive:jobdescriptor:3.8"
     xsi:schemaLocation="urn:proactive:jobdescriptor:3.8 http://www.activeeon.com/public_content/schemas/proactive/jobdescriptor/3.8/schedulerjob.xsd"
    name="test" projectName="test"
    priority="normal"
    onTaskError="continueJobExecution"
     maxNumberOfExecution="2"
>
  <taskFlow>
    <task name="Linux_Bash_Task">
      <description>
        <![CDATA[ The simplest task, ran by a bash engine. ]]>
      </description>
      <selection>
        <script
         type="static" >
          <code language="">
            <![CDATA[
foo
]]>
          </code>
        </script>
      </selection>
      <scriptExecutable>
        <script>
          <code language="bash">
            <![CDATA[
ls -la
]]>
          </code>
        </script>
      </scriptExecutable>
    </task>
  </taskFlow>
</job>`

**Comment by bamedro** [comment]
Attached file is causing this issue:

[test.txt](https://github.com/ow2-proactive/scheduling/files/1299457/test.txt)

**Comment by fviale** [comment]
fixed
