### ISSUE TITLE
The scheduler log is overloaded with RESTEASY warnings

### ISSUE THREAD

**Issue by ShatalovYaroslav** [ow2-proactive/scheduling#2977]
In the log there are appearing next warnings more often then every second:
WARN      o.j.r.r.i18n] RESTEASY002142: Multiple resource methods match request. Selecting one.

This warning should be related to 
https://stackoverflow.com/questions/46081787/resteasy002142-multiple-resource-methods-match-request

The problem that the log is overloaded. It's not clear which micro-service cause this warning, as many services print their logs in scheduler log.

**Comment by fviale** [comment]
Duplicate of #2580
