### ISSUE TITLE
Cannot submit variables with job

### ISSUE THREAD

**Issue by Mykhailenko** [ow2-proactive/scheduling#2983]
When I send POST request `http://localhost:8080/rest/scheduler/submit;mykey=Hello`, server does not inject variables. Of course I put proper session id, content-type as 'multipart/form-data', and in the body I put parameter 'file' as a string as in attached file. [printMyKey.txt](https://github.com/ow2-proactive/scheduling/files/1418176/printMyKey.txt)
Basically I want to submit a job which prints parameter 'mykey'. 
After I debug a bit, I found out that variable map with [mykey -> Hello] is properly sent to the scheduler. In  StaxJobFactory::createAndFillJob method 'replacementVariables' is actually never used (line 355 is never called)

Originally, I wanted to use this method: 'SystemTestRestJobHelper::submit(String sessionId, String jobFilePath, Map<String, String> variables)', which submit job as I showed above.

**Comment by tobwiens** [comment]
The scheduler only injects variables if those are "activated". A workflow needs to have at least one variable as a workflow variable, then you can inject all types of variables into that workflow.

**Comment by Mykhailenko** [comment]
Ok. I didn't know.

**Comment by fviale** [comment]
@tobwiens good find, the parser does not inject variables if it does not already contains the "variables" tag.
