### ISSUE TITLE
RM Rest API Scalibility could be drastically improved using GraphQL

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling#2987]
It would allow to perform partial requests to retrieve information about node status.
Today, REST API is really limited, and when having about 40,000 nodes, RM Portal triggers every 3 seconds a request which returns 8.5MB of data (frequency is updatable from the Portal > Settings).
This json payload is then zipped, so it will be smaller on the network. but anyway, it requires a lot of processing if you only need to get info on a subset of data).
GraphQL API are designed for such purpose

**Comment by fviale** [comment]
We improved with https://github.com/ow2-proactive/scheduling/commit/0bf1c949fb0bdd420a433492169c3f541fd7d33b vastly the amount of data transferred between the rm server and rm portal, maybe we should test in a big scale if the improvement works properly ?
