### ISSUE TITLE
proactive-server startup script should offer a rest-only option

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/scheduling#2989]
When deploying at scale, and offer better fault tolerance, it is better to separate the components.

Today, proactive-server startup script already support to start separately the 2 server components:
- RM (./proactive-server --no-router --no-discovery -ln 0 -c --rm-only)
- Scheduler+RM (./proactive-server --no-router -c --no-discovery -u pnp://rm:64738/)

We should also support to separate them in 3:
- RM (./proactive-server --no-router --no-discovery -ln 0 -c --rm-only)
- Scheduler (./proactive-server --no-router -no-rest -c --no-discovery -u pnp://rm:64738/)
- REST (./proactive-server --no-router --no-discovery -rest-only -u pnp://rm:64738/ --scheduler-url pnp://scheduler:64738)

It requires to add 2 options:
- rest-only
- scheduler-url

An explicit --scheduler-only would be convenient as well

**Comment by Mykhailenko** [comment]
Implemented (except `--schedulier-only`)
