### ISSUE TITLE
In SSHInfrastructure, the node process randomly cannot be started through JSch lib

### ISSUE THREAD

**Issue by jrochas** [ow2-proactive/scheduling#3023]
Sometimes the ssh connection opened to deploy nodes with an SSHInfrastructure-SSHInfrastructureV2 fails without obvious reason. 

```
[RM output]: Caused by: com.jcraft.jsch.JSchException: Session.connect: java.security.SignatureException: Invalid encoding for signature
[RM output]: 	at com.jcraft.jsch.Session.connect(Session.java:558)
[RM output]: 	at org.ow2.proactive.resourcemanager.nodesource.infrastructure.SSHInfrastructureV2.startNodeImpl(SSHInfrastructureV2.java:241)
```

The library that is used to open the ssh connection through java classes is the JSch library. The bug has been acknowledged by the library maintainers: 
https://sourceforge.net/p/jsch/bugs/111/

It happens most of the time when the functional tests are run by Jenkins (I was not able to reproduce locally)

**Comment by fviale** [comment]
Jsch has been upgraded since and the issue never appeared again
