### ISSUE TITLE
Using a long description at the workflow/task level drastically slow down the scheduler

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/scheduling#3028]
To reproduce it, just submit a workflow with 2-3 lines of description at the workflow/task level.

**Comment by fviale** [comment]
The issue is how the description is stored in the database. It is currently stored as a VARCHAR(255). It means that when we provide a description longer than 255 characters, it produces an error in the database, which causes big issues on the scheduler server because of transaction retries.

**Comment by fviale** [comment]
Duplicate of #3002

**Comment by fviale** [comment]
fixed by 
aebc2d4
