### ISSUE TITLE
RM: Property to clean down nodes and lost nodes after a time lapse

### ISSUE THREAD

**Issue by gparanthoen** [ow2-proactive/scheduling#3093]
A customer has its previous docker defunct nodes going down has the connexion is no longer good. 
The RM behaves correctly, However we could implement a new property to clean down nodes and lost nodes after a time lapse to avoid the customer for cleaning manually his nodes.

**Comment by fviale** [comment]
good idea

**Comment by jrochas** [comment]
@gparanthoen Implemented in https://github.com/ow2-proactive/scheduling/pull/3312
Please use now the resource manager properties:

- pa.rm.nodes.unavailable.removal.frequency=*/30 * * * *
- pa.rm.nodes.unavailable.maxperiod=1440

Default values specify an automatic cleaning, every 30 minutes, of down and lost nodes that are in this state for more than 24 hours.
