### ISSUE TITLE
version 8.3.2 : The RM bug when adding a new node source on Azure 

### ISSUE THREAD

**Issue by gparanthoen** [ow2-proactive/scheduling#3367]
###Context : 
The RM went down when I added an Azure scale set on try, and on tryqa with the version 8.3.2
there are no issues when doing it on version 8.3.0

I was using an elastic Azure scale set with a max of 10 nodes and minimum 0 node.  
after deployment, the 10 nodes are visible with the statut free *BUT there are 10 other nodes added with status in deployment. *
normal behaviore : 10 nodes free only. 

after removing the node set, the 10 nodes deployed are removed *BUT the 10 other nodes in deployment are still displayed in the graph "node history" and the rm start to not work properly* : 
1. error label displayed on top left hand side during 10 s
2. nodes not displayed on the grid view
3. instability on the rm
![image](https://user-images.githubusercontent.com/25740297/46673168-73721c00-cbd9-11e8-8166-cd2504d0b78d.png)

###Step to reproduce
- using version 8.3.2 and PAMR conf
- add an azure elastic node source
- launch a workflow that will trigger the deployment of azure nodes (depending on the load on the scheduler) 
- when the nodes are deployed, you should see new nodes added with status deploying. there should be the same number of node deployed and deploying. 
- remove the node source, node with status deploying should be still visible in the graph on the bottom right hand side. 
- you should see instabilities aswell. 
Please describe the problem in detail. Be sure to include:

- Expected behavior and actual behavior.
- Steps to reproduce the problem.
- Specifications (ProActive version, Operating system, Distributed setup, etc.).

**Comment by Mykhailenko** [comment]
Fixed.
Version: 8.3.3 or 8.4.0.
Commit : https://github.com/ow2-proactive/scheduling/commit/ed333d6eb548198aa0ccf74f47dd528f19000c90
