### ISSUE TITLE
Too long job's vars prevent it from submission

### ISSUE THREAD

**Issue by Mykhailenko** [ow2-proactive/scheduling#3438]
Job with too long variables cannot be submitted. 

Steps to reproduce:
1. open studio
2. open workflow
3. import [michael.xml](https://github.com/ow2-proactive/scheduling/files/2675376/michael.txt) as workflow
4. submit it
5. observe that workflow is not submitted (you get time-out error)

**Comment by fviale** [comment]
Fixed in 13.0.0 release
