### ISSUE TITLE
Scheduler.getTasksToSchedule() fails with stackoverflow

### ISSUE THREAD

**Issue by Mykhailenko** [ow2-proactive/scheduling#3491]
DynamicPolicy calls Scheduler::getTasksToSchedule() method. 
It returns list of tasks. However, due to AO communication, this list of task should be serialized.
If some task has too many kids of kids, serialization mechanism fails with stackoverflow.

Issue appears on tryqa with sometime. Possible job-planner construct some huge job.

**Comment by fviale** [comment]
fixed by 53ed2f6189f28dac3dff91f902de6b4cabf07952
