### ISSUE TITLE
resultMap binding accepts only string variables

### ISSUE THREAD

**Issue by aminelouati** [ow2-proactive/scheduling#3526]
Actually, the current implementation of resultMap accepts only string variables. However, the aim of this binding is to store interesting values which can be string, int, float or any serializable object to be used for job analytics. 
To reproduce the problem, submit a workflow that initializes resultMap with a non String variable (ex. resultMap.put("VAR", 12)) 

``` [{"exception":{"cause":null, "stackTrace":[], "message":null, "localizedMessage":null, "suppressed":[]}, "errorType":"DataFetchingException", "message":"Exception while fetching data: java.lang.ClassCastException", "locations":null}]```

Please refer to this commit as a starter point. 
https://github.com/ow2-proactive/scheduling/commit/03c17cc85b2b2be58a1afaa7333fcc9183eb9419

**Comment by Mykhailenko** [comment]
Fixed in https://github.com/ow2-proactive/scheduling-api/commit/d191053342910a69d89dbf95b61f3096ed6fc649
