### ISSUE TITLE
Default value for RMURL in all infrastructure managers leads to NPE

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/scheduling#777]
<a href="https://jira.activeeon.com/browse/SCHEDULING-826" title="SCHEDULING-826">Original issue</a> created by <a href="mailto:christian.delbe_AT_activeeon.com">Christian Delbé</a> on 08, Sep 2010 at 17:42 PM - SCHEDULING-826

<hr />

RMUrl is initialized with  
protected String rmUrl = PAActiveObject.getActiveObjectNodeUrl(PAActiveObject.getStubOnThis()).replace(
            PAResourceManagerProperties.RM_NODE_NAME.getValueAsString(), "");

PAActiveObject.getStubOnThis() returns null when using the console since the PluginDescriptor constructor is called from a simple thread (i.e. not an active object).
In the RCP, all the possible infrastructure are instanciated on RMCore side and send as a result of getAvailableInfrastrcture.

**Comment by Ilimbek99** [comment]
Macbook
